name: Daily News Sender

on:
  schedule:
    - cron: "*/3 * * * *"
  workflow_dispatch:

jobs:
  send-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run daily_news_sender.py
        env:
          NEWSAPI_API_KEY: ${{ secrets.NEWSAPI_API_KEY }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: python email_sender.py
